use_frameworks!

platform :ios, '10.0'

target 'CYNetworking_Example' do
  pod 'CYNetworking', :path => '../'

  target 'CYNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
